# Generated by Django 4.2.4 on 2023-08-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='edad_de_matrimonio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
