# Generated by Django 4.2.4 on 2023-08-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_alter_familiar_edad_de_matrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.IntegerField(default=2),
        ),
    ]
